def generate_guaranteed_presentation(topic: str) -> str:
    topic_url = topic.replace(' ', '+')
    parts = [
        '<!DOCTYPE html><html lang="es"><head>',
        '<meta charset="UTF-8">',
        '<meta name="viewport" content="width=device-width, initial-scale=1.0">',
        '<title>' + topic + ' - Presentacion Interactiva</title>',
        '<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/reveal.js@4.5.0/dist/reveal.css">',
        '<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/reveal.js@4.5.0/dist/theme/black.css">',
        '<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">',
        '<style>',
        '.reveal .slides section { padding: 40px; }',
        '.reveal h1, .reveal h2, .reveal h3 { text-transform: none; }',
        '.autor-card { background: rgba(255,255,255,0.1); border-radius: 20px; padding: 20px; margin-top: 30px; }',
        '.quiz-option { background: rgba(255,255,255,0.1); padding: 15px; margin: 10px 0; border-radius: 10px; cursor: pointer; transition: all 0.3s; }',
        '.quiz-option:hover { background: rgba(255,255,255,0.2); transform: scale(1.02); }',
        '.correct { background: #4ade80 !important; }',
        '.incorrect { background: #ef4444 !important; }',
        '.grid-2 { display: grid; grid-template-columns: 1fr 1fr; gap: 1rem; margin-top: 1rem; }',
        '.card-item { background: rgba(255,255,255,0.1); padding: 1rem; border-radius: 10px; }',
        '</style></head><body>',
        '<div class="reveal"><div class="slides">',

        # Slide 1: Cover
        '<section>',
        '<h1 class="fragment fade-up">' + topic + '</h1>',
        '<p class="fragment fade-up" style="font-size:1.3rem;margin-top:1rem;">Clase interactiva generada con IA</p>',
        '<div class="autor-card fragment fade-up" style="text-align:center">',
        '<a href="https://www.linkedin.com/in/johan-tapia-192183281/" target="_blank" style="color:#0077b5;margin:0 10px;font-size:2rem"><i class="fab fa-linkedin"></i></a>',
        '<a href="https://wa.me/18098684994" target="_blank" style="color:#25D366;margin:0 10px;font-size:2rem"><i class="fab fa-whatsapp"></i></a>',
        '<a href="mailto:johantbueno@gmail.com" style="color:#ea4335;margin:0 10px;font-size:2rem"><i class="fas fa-envelope"></i></a>',
        '<p style="margin-top:10px">Johan Tapia, PhD</p>',
        '</div></section>',

        # Slide 2: Objectives
        '<section>',
        '<h2>&#127919; Objetivos de Aprendizaje</h2>',
        '<ul style="list-style:none;margin-top:2rem">',
        '<li class="fragment fade-right">&#10003; Comprender el alcance y contexto de la materia</li>',
        '<li class="fragment fade-right">&#10003; Identificar los conceptos fundamentales del tema</li>',
        '<li class="fragment fade-right">&#10003; Conocer los procedimientos y principios aplicables</li>',
        '<li class="fragment fade-right">&#10003; Aplicar los conocimientos en casos practicos</li>',
        '</ul></section>',

        # Slide 3: Key Concepts
        '<section>',
        '<h2>&#128203; Conceptos Clave</h2>',
        '<div class="grid-2">',
        '<div class="card-item fragment fade-up"><i class="fas fa-lightbulb"></i> Fundamentos teoricos</div>',
        '<div class="card-item fragment fade-up"><i class="fas fa-cogs"></i> Aplicaciones practicas</div>',
        '<div class="card-item fragment fade-up"><i class="fas fa-book"></i> Marco normativo</div>',
        '<div class="card-item fragment fade-up"><i class="fas fa-users"></i> Perspectiva social</div>',
        '<div class="card-item fragment fade-up"><i class="fas fa-chart-bar"></i> Indicadores clave</div>',
        '<div class="card-item fragment fade-up"><i class="fas fa-globe"></i> Contexto global</div>',
        '</div></section>',

        # Slide 4: Quiz
        '<section>',
        '<h2>&#9999; Evaluacion Rapida</h2>',
        '<div id="quiz-container" style="margin-top:2rem">',
        '<div id="quiz-question" style="font-size:1.1rem;font-weight:bold"></div>',
        '<div id="quiz-options" style="margin-top:1rem"></div>',
        '<div id="quiz-feedback" style="margin-top:1rem"></div>',
        '</div></section>',

        # Slide 5: Resources
        '<section>',
        '<h2>&#128218; Recursos Adicionales</h2>',
        '<div style="text-align:left;margin-top:1rem">',
        '<div class="fragment fade-up" style="margin-bottom:1rem">',
        '<i class="fab fa-youtube" style="color:#ff0000"></i>',
        '<a href="https://www.youtube.com/results?search_query=' + topic_url + '" target="_blank" style="margin-left:8px">Videos educativos en YouTube</a>',
        '</div>',
        '<div class="fragment fade-up" style="margin-bottom:1rem">',
        '<i class="fas fa-book" style="color:#7c3aed"></i>',
        '<span style="margin-left:8px">Bibliografia recomendada del curso</span>',
        '</div>',
        '<div class="fragment fade-up" style="margin-bottom:1rem">',
        '<i class="fas fa-university" style="color:#14b8a6"></i>',
        '<span style="margin-left:8px">Materiales del campus virtual Moodle</span>',
        '</div>',
        '</div></section>',

        # Slide 6: Author
        '<section>',
        '<h2>&#128104;&#8205;&#127979; Sobre el Autor</h2>',
        '<div style="text-align:center;margin-top:1rem">',
        '<div style="width:80px;height:80px;background:linear-gradient(135deg,#7c3aed,#14b8a6);border-radius:50%;margin:0 auto 1rem;display:flex;align-items:center;justify-content:center;font-size:2rem">',
        '<i class="fas fa-user-graduate"></i></div>',
        '<h3>Johan Tapia, PhD</h3>',
        '<p>Especialista en Educacion y Tecnologia</p>',
        '<div style="margin-top:1rem">',
        '<a href="https://www.linkedin.com/in/johan-tapia-192183281/" target="_blank" style="color:#0077b5;font-size:1.5rem;margin:0 8px"><i class="fab fa-linkedin"></i></a>',
        '<a href="https://wa.me/18098684994" target="_blank" style="color:#25D366;font-size:1.5rem;margin:0 8px"><i class="fab fa-whatsapp"></i></a>',
        '<a href="mailto:johantbueno@gmail.com" style="color:#ea4335;font-size:1.5rem;margin:0 8px"><i class="fas fa-envelope"></i></a>',
        '</div>',
        '<p style="margin-top:1rem;font-size:0.8rem;opacity:0.7">Generado con JT AI Suite</p>',
        '</div></section>',

        '</div></div>',
        '<script src="https://cdn.jsdelivr.net/npm/reveal.js@4.5.0/dist/reveal.js"></script>',
        '<script>',
        'Reveal.initialize({controls:true,progress:true,center:true,hash:true,slideNumber:true,transition:"slide"});',
        'const questions=[',
        '{question:"Cual es el concepto mas importante del tema estudiado?",options:["Fundamentos teoricos","Aplicaciones practicas","Marco normativo","Todos los anteriores"],correct:3},',
        '{question:"Por que es importante conocer este tema?",options:["Solo academicamente","Solo profesionalmente","Academica y profesionalmente","No tiene importancia"],correct:2},',
        '{question:"Como se aplican estos conocimientos?",options:["Solo en teoria","En casos reales y situaciones profesionales","No se aplican","Solo en examenes"],correct:1}',
        '];',
        'let cur=0;',
        'function loadQ(){',
        'if(cur>=questions.length){document.getElementById("quiz-container").innerHTML="<p style=\'color:#4ade80;font-size:1.3rem\'>Felicidades! Completaste el quiz.</p>";return;}',
        'const q=questions[cur];',
        'document.getElementById("quiz-question").textContent=(cur+1)+". "+q.question;',
        'const div=document.getElementById("quiz-options");div.innerHTML="";',
        'q.options.forEach((opt,i)=>{',
        'const b=document.createElement("div");b.className="quiz-option";',
        'b.textContent=String.fromCharCode(65+i)+". "+opt;',
        'b.onclick=()=>{',
        'if(i===q.correct){b.classList.add("correct");document.getElementById("quiz-feedback").innerHTML="<p style=\'color:#4ade80\'>Correcto!</p>";setTimeout(()=>{cur++;loadQ();},1500);}',
        'else{b.classList.add("incorrect");document.getElementById("quiz-feedback").innerHTML="<p style=\'color:#ef4444\'>Incorrecto. Era: "+q.options[q.correct]+"</p>";setTimeout(()=>{b.classList.remove("incorrect");document.getElementById("quiz-feedback").innerHTML="";},2000);}',
        '};',
        'div.appendChild(b);',
        '});',
        'document.getElementById("quiz-feedback").innerHTML="";',
        '}',
        'loadQ();',
        '</script></body></html>'
    ]
    return '\n'.join(parts)
